version: "3.8"
services:
  dev-connector-service:
    build: ./dev-connector-service
    ports:
      - 3000:3000
    depends_on:
      - mongo
    volumes:
      - ./dev-connector-service:/app
    command: npm run dev

  mongo:
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
