version: "3.8"
services:
  dev-connector-service:
    build: ./dev-connector-service
    ports:
      - 3000:3000
    depends_on:
      - mongo
    profiles:
      - services
  mongo:
    image: mongo:5.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
